import Image from "next/image";
import Cover from "../../../../images/slider/travel.jpg";
export default function Blog3(){
    return(
        <div className="blog-body">
            <div className="blog">
                <div className="tittle">
                    <h1>Tittle of Blog</h1>
                </div>
                <div className="image">
                <Image src = {Cover} alt="Img not"/>
                </div>
                <h1>Tittle Of the Blog</h1><br /><br />
                <p><span className="first-letter">L</span>orem ipsum, dolor sit amet consectetur adipisicing elit. Nemo corrupti soluta accusamus hic officia? Culpa deleniti quidem dolor odio delectus. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus rem minus placeat quo laborum libero veritatis dolor voluptatem atque inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident voluptatem earum nobis aspernatur hic esse repudiandae facere ab nostrum. <br /><br /><br /></p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo corrupti soluta accusamus hic officia? Culpa deleniti quidem dolor odio delectus. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus rem minus placeat quo laborum libero veritatis dolor voluptatem atque inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident voluptatem earum nobis aspernatur hic esse repudiandae facere ab nostrum. <br /><br /><br /></p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo corrupti soluta accusamus hic officia? Culpa deleniti quidem dolor odio delectus. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus rem minus placeat quo laborum libero veritatis dolor voluptatem atque inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident voluptatem earum nobis aspernatur hic esse repudiandae facere ab nostrum. <br /><br /><br /></p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo corrupti soluta accusamus hic officia? Culpa deleniti quidem dolor odio delectus. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus rem minus placeat quo laborum libero veritatis dolor voluptatem atque inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident voluptatem earum nobis aspernatur hic esse repudiandae facere ab nostrum. <br /><br /></p>
                <h2>Subtittle</h2>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo corrupti soluta accusamus hic officia? Culpa deleniti quidem dolor odio delectus. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus rem minus placeat quo laborum libero veritatis dolor voluptatem atque inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident voluptatem earum nobis aspernatur hic esse repudiandae facere ab nostrum. <br /><br /><br /></p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo corrupti soluta accusamus hic officia? Culpa deleniti quidem dolor odio delectus. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus rem minus placeat quo laborum libero veritatis dolor voluptatem atque inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident voluptatem earum nobis aspernatur hic esse repudiandae facere ab nostrum. <br /><br /><br /></p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo corrupti soluta accusamus hic officia? Culpa deleniti quidem dolor odio delectus. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus rem minus placeat quo laborum libero veritatis dolor voluptatem atque inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident voluptatem earum nobis aspernatur hic esse repudiandae facere ab nostrum. <br /><br /><br /></p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo corrupti soluta accusamus hic officia? Culpa deleniti quidem dolor odio delectus. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus rem minus placeat quo laborum libero veritatis dolor voluptatem atque inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident voluptatem earum nobis aspernatur hic esse repudiandae facere ab nostrum. <br /><br /></p>
                <h2>Subtittle</h2>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo corrupti soluta accusamus hic officia? Culpa deleniti quidem dolor odio delectus. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus rem minus placeat quo laborum libero veritatis dolor voluptatem atque inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident voluptatem earum nobis aspernatur hic esse repudiandae facere ab nostrum. <br /><br /><br /></p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo corrupti soluta accusamus hic officia? Culpa deleniti quidem dolor odio delectus. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus rem minus placeat quo laborum libero veritatis dolor voluptatem atque inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident voluptatem earum nobis aspernatur hic esse repudiandae facere ab nostrum. <br /><br /><br /></p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo corrupti soluta accusamus hic officia? Culpa deleniti quidem dolor odio delectus. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus rem minus placeat quo laborum libero veritatis dolor voluptatem atque inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident voluptatem earum nobis aspernatur hic esse repudiandae facere ab nostrum. <br /><br /><br /></p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo corrupti soluta accusamus hic officia? Culpa deleniti quidem dolor odio delectus. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus rem minus placeat quo laborum libero veritatis dolor voluptatem atque inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident voluptatem earum nobis aspernatur hic esse repudiandae facere ab nostrum. <br /><br /></p>
                <h2>Subtittle</h2>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo corrupti soluta accusamus hic officia? Culpa deleniti quidem dolor odio delectus. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus rem minus placeat quo laborum libero veritatis dolor voluptatem atque inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident voluptatem earum nobis aspernatur hic esse repudiandae facere ab nostrum. <br /><br /><br /></p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo corrupti soluta accusamus hic officia? Culpa deleniti quidem dolor odio delectus. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus rem minus placeat quo laborum libero veritatis dolor voluptatem atque inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident voluptatem earum nobis aspernatur hic esse repudiandae facere ab nostrum. <br /><br /><br /></p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo corrupti soluta accusamus hic officia? Culpa deleniti quidem dolor odio delectus. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus rem minus placeat quo laborum libero veritatis dolor voluptatem atque inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident voluptatem earum nobis aspernatur hic esse repudiandae facere ab nostrum. <br /><br /><br /></p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo corrupti soluta accusamus hic officia? Culpa deleniti quidem dolor odio delectus. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus rem minus placeat quo laborum libero veritatis dolor voluptatem atque inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident voluptatem earum nobis aspernatur hic esse repudiandae facere ab nostrum. <br /><br /></p>
                <h2>Subtittle</h2>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo corrupti soluta accusamus hic officia? Culpa deleniti quidem dolor odio delectus. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus rem minus placeat quo laborum libero veritatis dolor voluptatem atque inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident voluptatem earum nobis aspernatur hic esse repudiandae facere ab nostrum. <br /><br /><br /></p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo corrupti soluta accusamus hic officia? Culpa deleniti quidem dolor odio delectus. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus rem minus placeat quo laborum libero veritatis dolor voluptatem atque inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident voluptatem earum nobis aspernatur hic esse repudiandae facere ab nostrum. <br /><br /><br /></p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo corrupti soluta accusamus hic officia? Culpa deleniti quidem dolor odio delectus. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus rem minus placeat quo laborum libero veritatis dolor voluptatem atque inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident voluptatem earum nobis aspernatur hic esse repudiandae facere ab nostrum. <br /><br /><br /></p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo corrupti soluta accusamus hic officia? Culpa deleniti quidem dolor odio delectus. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus rem minus placeat quo laborum libero veritatis dolor voluptatem atque inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident voluptatem earum nobis aspernatur hic esse repudiandae facere ab nostrum. <br /><br /><br /></p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo corrupti soluta accusamus hic officia? Culpa deleniti quidem dolor odio delectus. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus rem minus placeat quo laborum libero veritatis dolor voluptatem atque inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident voluptatem earum nobis aspernatur hic esse repudiandae facere ab nostrum. <br /><br /></p>
                <h2>Subtittle</h2>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo corrupti soluta accusamus hic officia? Culpa deleniti quidem dolor odio delectus. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus rem minus placeat quo laborum libero veritatis dolor voluptatem atque inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident voluptatem earum nobis aspernatur hic esse repudiandae facere ab nostrum. <br /><br /><br /></p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo corrupti soluta accusamus hic officia? Culpa deleniti quidem dolor odio delectus. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus rem minus placeat quo laborum libero veritatis dolor voluptatem atque inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident voluptatem earum nobis aspernatur hic esse repudiandae facere ab nostrum. <br /><br /><br /></p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo corrupti soluta accusamus hic officia? Culpa deleniti quidem dolor odio delectus. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus rem minus placeat quo laborum libero veritatis dolor voluptatem atque inventore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident voluptatem earum nobis aspernatur hic esse repudiandae facere ab nostrum. <br /><br /><br /></p>
                                
            </div>
        </div>
    )
}